In [12]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# **IMPORTING THE DATA FILE**

In [13]:
df =  pd.read_csv('iris.csv')

In [14]:
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2     0.0
1                4.9               3.0  ...               0.2     0.0
2                4.7               3.2  ...               0.2     0.0
3                4.6               3.1  ...               0.2     0.0
4                5.0               3.6  ...               0.2     0.0

[5 rows x 5 columns]

In [15]:
df.shape

(150, 5)

# **SPLITTING INTO TRAINING AND TEST SET**

In [16]:
from sklearn.model_selection import train_test_split

In [24]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=33)

In [36]:
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

# **IMPORTING USING PYTORCH**

In [38]:
from torch.utils.data import TensorDataset,DataLoader

In [40]:
iris = TensorDataset(torch.FloatTensor(X),torch.LongTensor(y))

In [43]:
for i in iris:
  print(i)

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0))
(tensor([5.4000, 3.7000, 1.5000, 0.2000]), tensor(0))
(tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0))
(tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0))
(tensor([4.3000, 3.0000, 1.1000, 0.1000]), tensor(0))
(tensor([5.8000, 4.0000, 1.2000, 0.2000]), tensor(0))
(tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0))
(tensor([5.4000, 3.9000, 1.3000, 0.4000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.3000]), tensor(0))
(tensor([5.7000, 3.8000, 1.7

In [44]:
iris_loader = DataLoader(iris,batch_size=50,shuffle=True)
for i_batch,sample_batch in iris_loader:
  print(i_batch,sample_batch)

tensor([[4.7000, 3.2000, 1.6000, 0.2000],
        [5.2000, 4.1000, 1.5000, 0.1000],
        [6.0000, 2.2000, 4.0000, 1.0000],
        [5.1000, 3.8000, 1.6000, 0.2000],
        [5.4000, 3.0000, 4.5000, 1.5000],
        [6.8000, 2.8000, 4.8000, 1.4000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [5.2000, 3.4000, 1.4000, 0.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [6.3000, 3.3000, 4.7000, 1.6000],
        [7.2000, 3.2000, 6.0000, 1.8000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [5.6000, 2.7000, 4.2000, 1.3000],
        [6.1000, 2.8000, 4.7000, 1.2000],
        [6.3000, 2.5000, 5.0000, 1.9000],
        [5.8000, 2.7000, 3.9000, 1.2000],
        [4.4000, 3.0000, 1.3000, 0.2000],
        [6.7000, 3.3000, 5.7000, 2.1000],
        [5.7000, 2.6000, 3.5000, 1.0000],
        [6.3000, 2.7000, 4.9000, 1.8000],
        [5.5000, 2.4000, 3.8000, 1.1000],
        [6.2000, 2.8000, 4.8000, 1.8000],
        [7.7000, 2.6000, 6.9000, 2